#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rb-fsevent
Version  : 0.9.7
Release  : 4
URL      : https://rubygems.org/downloads/rb-fsevent-0.9.7.gem
Source0  : https://rubygems.org/downloads/rb-fsevent-0.9.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core

%description
[![Code Climate](https://codeclimate.com/badge.png)](https://codeclimate.com/github/thibaudgg/rb-fsevent)
[![endorse](https://api.coderwall.com/ttilley/endorsecount.png)](https://coderwall.com/ttilley)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rb-fsevent-0.9.7
gem spec %{SOURCE0} -l --ruby > rubygem-rb-fsevent.gemspec

%build
gem build rubygem-rb-fsevent.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rb-fsevent-0.9.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rb-fsevent-0.9.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/FSEventsFix.c
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/FSEventsFix.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/TSICTString.c
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/TSICTString.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/cli.c
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/cli.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/common.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/compat.c
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/compat.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/defines.h
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/fsevent_watch/main.c
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/ext/rakefile.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/rb-fsevent.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/rb-fsevent-0.9.7.gemspec
